/**
 * Hold reason value object + collection helpers.
 *
 * A `HoldReason` records that a domain document is blocked from progressing
 * until the hold is resolved. The primitive is *pure data + pure helpers* —
 * no FSM, no persistence, no events. Hosts embed `HoldReason[]` on their
 * documents and use the helpers to add / resolve / query.
 *
 * Consumers: `@classytic/order` (fraud, manual, payment, credit, inventory
 * holds), `@classytic/flow` (quality hold, customs hold), `@classytic/revenue`
 * (chargeback hold).
 *
 * @example
 * import { addHold, resolveHold, activeHolds, isOnHold } from '@classytic/primitives/hold';
 *
 * let holds = addHold([], {
 *   code: 'credit_check_failed',
 *   note: 'customer exceeds $50k limit',
 *   actor: { id: 'system', kind: 'system' },
 * });
 * isOnHold(holds); // true
 * holds = resolveHold(holds, holds[0].id, { actor: { id: 'user_42', kind: 'user' }, note: 'override approved' });
 * isOnHold(holds); // false
 */

export type HoldActorKind = 'user' | 'system' | 'service';

export interface HoldActor {
  readonly id: string;
  readonly kind: HoldActorKind;
  readonly name?: string;
}

export interface HoldReason {
  /**
   * Unique identifier within the collection — used to resolve a specific hold
   * when multiple are active. Generated by {@link addHold} if caller omits it.
   */
  readonly id: string;
  /** Domain-defined stable code, e.g. `fraud_review`, `customs_detention`. */
  readonly code: string;
  readonly note?: string;
  readonly actor: HoldActor;
  readonly createdAt: Date;
  readonly resolvedAt?: Date;
  readonly resolvedBy?: HoldActor;
  readonly resolutionNote?: string;
  readonly metadata?: Readonly<Record<string, unknown>>;
}

export type HoldErrorCode =
  | 'UNKNOWN_HOLD_ID'
  | 'ALREADY_RESOLVED'
  | 'INVALID_CODE'
  | 'DUPLICATE_HOLD_ID';

export class HoldError extends Error {
  override readonly name = 'HoldError';
  readonly code: HoldErrorCode;

  constructor(code: HoldErrorCode, message: string) {
    super(message);
    this.code = code;
  }
}

export interface AddHoldInput {
  readonly id?: string;
  readonly code: string;
  readonly note?: string;
  readonly actor: HoldActor;
  readonly createdAt?: Date;
  readonly metadata?: Readonly<Record<string, unknown>>;
}

export interface ResolveHoldInput {
  readonly actor: HoldActor;
  readonly note?: string;
  readonly resolvedAt?: Date;
}

/**
 * Add a new hold to the collection. Returns a new array — original is not
 * mutated. `id` is generated if omitted (stable format: `hold_{epochMs}_{rand}`).
 */
export function addHold(holds: readonly HoldReason[], input: AddHoldInput): readonly HoldReason[] {
  if (!input.code || input.code.trim() === '') {
    throw new HoldError('INVALID_CODE', 'hold code must be a non-empty string');
  }
  const id = input.id ?? generateHoldId();
  if (holds.some((h) => h.id === id)) {
    throw new HoldError('DUPLICATE_HOLD_ID', `hold id already present: ${id}`);
  }
  const hold: HoldReason = {
    id,
    code: input.code,
    ...(input.note !== undefined ? { note: input.note } : {}),
    actor: input.actor,
    createdAt: input.createdAt ?? new Date(),
    ...(input.metadata !== undefined ? { metadata: input.metadata } : {}),
  };
  return [...holds, hold];
}

/**
 * Resolve a specific hold by id. Throws if the id is unknown or the hold is
 * already resolved.
 */
export function resolveHold(
  holds: readonly HoldReason[],
  id: string,
  input: ResolveHoldInput,
): readonly HoldReason[] {
  const index = holds.findIndex((h) => h.id === id);
  if (index === -1) {
    throw new HoldError('UNKNOWN_HOLD_ID', `no hold with id ${id}`);
  }
  const hold = holds[index];
  if (!hold) {
    throw new HoldError('UNKNOWN_HOLD_ID', `no hold with id ${id}`);
  }
  if (hold.resolvedAt !== undefined) {
    throw new HoldError('ALREADY_RESOLVED', `hold ${id} is already resolved`);
  }
  const resolved: HoldReason = {
    ...hold,
    resolvedAt: input.resolvedAt ?? new Date(),
    resolvedBy: input.actor,
    ...(input.note !== undefined ? { resolutionNote: input.note } : {}),
  };
  return holds.map((h, i) => (i === index ? resolved : h));
}

/** All holds that have not yet been resolved. */
export function activeHolds(holds: readonly HoldReason[]): readonly HoldReason[] {
  return holds.filter((h) => h.resolvedAt === undefined);
}

/** True if at least one active (unresolved) hold exists. */
export function isOnHold(holds: readonly HoldReason[]): boolean {
  return holds.some((h) => h.resolvedAt === undefined);
}

/**
 * True if at least one active hold matches the given code. Useful for checking
 * for a specific class of hold (e.g., "is this order on a fraud hold?").
 */
export function hasActiveHoldOfCode(holds: readonly HoldReason[], code: string): boolean {
  return holds.some((h) => h.resolvedAt === undefined && h.code === code);
}

/** All resolved holds — useful for audit timelines. */
export function resolvedHolds(holds: readonly HoldReason[]): readonly HoldReason[] {
  return holds.filter((h) => h.resolvedAt !== undefined);
}

// Sufficiently unique for within-document IDs. Not cryptographic — host
// can substitute its own generator via the `id` input if collisions matter.
function generateHoldId(): string {
  const ms = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 10);
  return `hold_${ms}_${rand}`;
}
